### PR TITLE
#87 youtube video quality ensure videos download at max quality

### LINKED ISSUE #87: YouTube Video Quality
If possible, consider adding the option of controlling the quality of videos that are being downloaded from YouTube. Or simply ensure that all the videos are being downloaded in _MAX_ quality. 

Currently, YouTube has put restrictions on their video quality due to excessive rush on the website because of the coronavirus lockdown. The default video quality is low. Udacimak, in turn, is downloading all the videos in low quality as well.

If there is a workaround for this problem, then please let me know.

### PR DESCRIPTION
**Pull request by CodigoMatriz**
# Description

Updated the code to use the `youtube-dl` binary as this allows to download the max quality video and audio and be merged into one `mp4` file.

Fixes #87 

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

Ran the application as intended and functionality stayed the same, with the exception that videos are now downloaded at max quality -- 1080p in my case.

# Configurations
 - OS: macOS 10.15.3
 - Node version: v11.15.0
 - npm version: 6.7.0

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by udacimak** [comment]
Thanks @CodigoMatriz 
I'd like to keep the download progress bar, is there a reason why it has been removed? Could you add it back?

**Comment by Kahol-g** [comment]
@CodigoMatriz thanks for the PR but check out this [answer](https://askubuntu.com/a/1097056/327339), It turns out  'bestvideo+bestaudio' is not the accurate solution to obtain the max quality video from youtube

**Comment by CodigoMatriz** [comment]
@Kahol-g I went back and read the documentation for youtube-dl I don't even have to pass the format at all, as the default behavior is `bestvideo+bestaudio/best`.

Excerpt from [Format Selection](https://github.com/ytdl-org/youtube-dl/blob/master/README.md#format-selection):
```Since the end of April 2015 and version 2015.04.26, youtube-dl uses -f bestvideo+bestaudio/best as the default format selection (see #5447, #5456). If ffmpeg or avconv are installed this results in downloading bestvideo and bestaudio separately and muxing them together into a single file giving the best overall quality available. Otherwise it falls back to best and results in downloading the best available quality served as a single file. best is also needed for videos that don't come from YouTube because they don't provide the audio and video in two different files.```

**Comment by CodigoMatriz** [comment]
> Thanks @CodigoMatriz
> I'd like to keep the download progress bar, is there a reason why it has been removed? Could you add it back?

@udacimak I'll take a look at this.

**Comment by Kahol-g** [comment]
`
> I tested with Data Structures & Algorithms, and it downloaded the complete course in 1080p, whereas before with best it was failing after two videos with a 500.

interesting... 
except the part of 500, the downloading quality was way contrary for me.
I was downloading frontend nanodegree, I got the  720p quality by passing the parameter  in PR and by totally eliminating the parameters,  I got 1080p  downloaded. So let me assume its dependent from course to course

**Comment by udacimak** [comment]
I was testing this pull request, but it still throws error in some cases:

```
× Getting Youtube video id FKcIJkTA3GI information
2020-04-07T09:20:18.785Z [error]: ERROR: Command failed with exit code 1: udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json -f best -f=bestvideo+bestaudio --encoding utf8 http://www.youtube.com/watch?v=FKcIJkTA3GI
STACK: Error: Command failed with exit code 1: udacimak\node_modules\youtube-dl\bin\youtube-dl.exe --dump-json -f best -f=bestvideo+bestaudio --encoding utf8 http://www.youtube.com/watch?v=FKcIJkTA3GI
    at makeError (udacimak\node_modules\execa\lib\error.js:56:11)
    at handlePromise (udacimak\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

@Kahol-g leaving the `format` parameter empty also throw the same error above for me.

I have used pull request #111 instead

`youtube-dl` sure does work in some mysterious way!

**Pull request closed without merging**
